/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/next`; params?: Router.UnknownInputParams; } | { pathname: `/places`; params?: Router.UnknownInputParams; } | { pathname: `/places/new`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/trips`; params?: Router.UnknownInputParams; } | { pathname: `/trips/new`; params?: Router.UnknownInputParams; } | { pathname: `/places/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/trips/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/next`; params?: Router.UnknownOutputParams; } | { pathname: `/places`; params?: Router.UnknownOutputParams; } | { pathname: `/places/new`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/trips`; params?: Router.UnknownOutputParams; } | { pathname: `/trips/new`; params?: Router.UnknownOutputParams; } | { pathname: `/places/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/trips/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/next${`?${string}` | `#${string}` | ''}` | `/places${`?${string}` | `#${string}` | ''}` | `/places/new${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/trips${`?${string}` | `#${string}` | ''}` | `/trips/new${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/next`; params?: Router.UnknownInputParams; } | { pathname: `/places`; params?: Router.UnknownInputParams; } | { pathname: `/places/new`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/trips`; params?: Router.UnknownInputParams; } | { pathname: `/trips/new`; params?: Router.UnknownInputParams; } | `/places/${Router.SingleRoutePart<T>}` | `/trips/${Router.SingleRoutePart<T>}` | { pathname: `/places/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/trips/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
